[package]
name = "thoughts-worker"
version = "0.1.0"
edition = "2024"

[features]
airports = ["thoughts-core/airports"]

[lib]
crate-type = ["cdylib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
thoughts-core = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen = "=0.2.126"
